- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - curl
      - git
      - libusb-1.0
      - net-tools
      - python3
      - python3-pip
      - screen
      - vim
