- hosts: localhost
  become: true
  module_defaults:
    apt:
      force_apt_get: yes
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/cron.yml
    - include: tasks/users.yml
    - include: tasks/copy_files.yml
