- name: copy vim file
  copy:
    src: configs/vimrc
    dest: /home/achou/.vimrc
    owner: achou
    group: achou
    mode: '0640'

- name: copy bashrc file
  copy:
    src: configs/bashrc
    dest: /home/achou/.bashrc
    owner: achou
    group: achou
    mode: '0640'

- name: copy screenrc file
  copy:
    src: configs/screenrc
    dest: /home/achou/.screenrc
    owner: achou
    group: achou
    mode: '0640'

- name: copy gitconfig file
  copy:
    src: configs/gitconfig
    dest: /home/achou/.gitconfig
    owner: achou
    group: achou
    mode: '0640'

