- name: Install packages
  apt: 
      state: latest 
      update_cache: yes
      name:
          - apt-transport-https
          - ca-certificates
          - colordiff
          - curl
          - git
          - gnupg2
          - jq
          - libusb-1.0-0
          - net-tools
          - python3
          - python3-pip
          - screen
          - software-properties-common
          - vim
          - whois

- name: nvm
  shell: >
    curl -o https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    warn: no

- name: Add Docker GPG key
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker-ce
  apt:
      state: latest
      update_cache: yes
      name: docker-ce
