- name: Install packages
  apt: 
      state: present
      name:
          - colordiff
          - curl
          - git
          - jq
          - libusb-1.0-0
          - net-tools
          - python3
          - python3-pip
          - screen
          - vim
