- name: Install packages
  apt: 
      state: present
      name:
          - colordiff
          - curl
          - git
          - gnupg2
          - jq
          - libusb-1.0-0
          - net-tools
          - python3
          - python3-pip
          - screen
          - vim
          - whois

- name: nvm
  shell: >
    curl -o https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
