# Setup vim
- name: copy vim file
  copy:
      src: configs/vimrc
      dest: /home/achou/.vimrc
      owner: achou
      group: achou
      mode: '0640'

- name: vim dirs
  file:
      path: "{{item}}"
      owner: achou
      group: achou
      mode: '0750'
      state: directory
  with_items:
      - '/home/achou/.vim'
      - '/home/achou/.vim/backups'
      - '/home/achou/.vim/swapfiles'
      - '/home/achou/.vim/autoload'

- name: Install vim-plug
  get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: /home/achou/.vim/autoload/plug.vim
      owner: achou
      group: achou
      mode: '0640'

      #- name: setup vim
      #  shell:  vim -c ':PlugInstall | :q | :q'
      #  args:
      #      executable: /bin/bash


- name: Create home dirs
  file:
      path: "/home/achou/{{ item }}"
      state: directory
      owner: achou
      group: achou
      mode: '0755'
  loop:
      - .ssh
      - .gnupg

- name: setup ssh
  copy:
      src: configs/authorized_keys
      dest: /home/achou/.ssh/authorized_keys
      owner: achou
      group: achou
      mode: '0440'

- name: copy bashrc file
  copy:
      src: configs/bashrc
      dest: /home/achou/.bashrc
      owner: achou
      group: achou
      mode: '0640'

- name: screenrc run dir
  file:
      path: /run/screen
      state: directory
      mode: '0777'

- name: copy screenrc file
  copy:
      src: configs/screenrc
      dest: /home/achou/.screenrc
      owner: achou
      group: achou
      mode: '0640'

- name: setup gpg
  copy:
    src: configs/gpg.conf
    dest: /home/achou/.gnupg/gpg.conf
    owner: achou
    group: achou
    mode: '0664'

# Configure git
- name: copy gitconfig file
  copy:
      src: configs/gitconfig
      dest: /home/achou/.gitconfig
      owner: achou
      group: achou
      mode: '0640'

- name: install git ps1
  get_url:
      url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
      dest: /home/achou/.git-prompt.sh
      owner: achou
      group: achou
      mode: '0640'

- name: install diff-so-fancy
  get_url:
      url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
      dest: /usr/local/bin/diff-so-fancy
      owner: root
      group: root
      mode: '755'

