- name: copy sudoers file
  copy:
    src: configs/achou_sudoers
    dest: /etc/sudoers.d/achou
    owner: root
    group: root
    mode: '0400'

- name: Add user to docker gorup
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes
