call plug#begin()
"Plug 'w0rp/ale'
"Plug 'vim-syntastic/syntastic'
Plug 'ntpeters/vim-better-whitespace'
Plug 'Vimjas/vim-python-pep8-indent'
Plug 'sheerun/vim-polyglot'
call plug#end()

set modeline
set hlsearch
set laststatus=2
set statusline=%F%m%r%h%w\ [format=%{&ff}]\ [type=%Y]\ [row,col=%04l,%03v]\ [%p%%]\ [len=%L]
set nonumber
set mouse=r
set wildmode=longest,list,full
set wildmenu
set completeopt=menu
" let g:vim_json_syntax_conceal = 0
filetype plugin indent on
set expandtab
set tw=0
set wrap
set ts=4
set sw=4
set ai
set backupdir=$HOME/.vim/backups//
set directory=$HOME/.vim/swapfiles//
au BufNewFile,BufReadPost Jenkinsfile* set syntax=groovy sw=4 ts=4
set ffs=unix " disable "file format = dos" detection

vnoremap <C-c> "+y
" Disable annoying auto line break
fu! DisableBr()
    set wrap
    set linebreak
    set nolist  " list disables linebreak
    set textwidth=0
    set wrapmargin=0
    set fo-=t
endfu
